# Generated by Django 5.1.2 on 2024-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoouser',
            name='icon',
            field=models.CharField(default='lion', max_length=64),
        ),
    ]
