# Generated by Django 5.1.2 on 2024-11-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooBooking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('zoo_booking_date', models.DateField(auto_now_add=True)),
                ('zoo_booking_date_arrive', models.DateField()),
                ('zoo_booking_date_leave', models.DateField()),
                ('zoo_booking_adults', models.IntegerField(default=0)),
                ('zoo_booking_children', models.IntegerField(default=0)),
                ('zoo_booking_oap', models.IntegerField(default=0)),
                ('zoo_total_cost', models.FloatField(default=0)),
                ('zoo_points', models.IntegerField(default=0)),
                ('zoo_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
