# Generated by Django 5.1.2 on 2024-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_zoouser_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_user_id', models.IntegerField()),
                ('hotel_booking_date', models.DateTimeField()),
                ('hotel_booking_date_arrive', models.DateTimeField()),
                ('hotel_booking_date_leave', models.DateTimeField()),
            ],
        ),
    ]
