# Generated by Django 5.1.2 on 2024-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_hotelbooking_hotel_booking_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_booking_date_arrive',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_booking_date_leave',
            field=models.DateField(),
        ),
    ]
